"""
Summarizer Agent — converts the RCA JSON into a clean markdown report.
Final node in the LangGraph workflow.
"""

from loguru import logger
from llm import call_gemini


def run_summarizer(state: dict) -> dict:
    """
    LangGraph node: Summarizer.
    Produces the final markdown incident report.
    """
    rca = state.get("rca", {})
    plan = state.get("plan", {})
    deployment_findings = state.get("deployment_findings", {})
    log_findings = state.get("log_findings", {})
    metrics_findings = state.get("metrics_findings", {})
    similar = state.get("similar_incidents", [])

    logger.info("[Summarizer] Generating final report...")

    root_cause = rca.get("root_cause", {})
    confidence = root_cause.get("confidence_pct", 0)
    evidence = root_cause.get("evidence", [])
    immediate_actions = rca.get("immediate_actions", [])
    prevention = rca.get("long_term_prevention", [])
    alt_hypotheses = rca.get("alternative_hypotheses", [])

    suspect = deployment_findings.get("suspect_deployment", {})

    # Build evidence bullets
    evidence_md = "\n".join([f"✅ {e}" for e in evidence]) if evidence else "See detailed findings above."

    # Build actions
    actions_md = "\n".join([f"{i+1}. {a}" for i, a in enumerate(immediate_actions)])
    prevention_md = "\n".join([f"- {p}" for p in prevention])

    # Alternative hypotheses
    alt_md = ""
    for alt in alt_hypotheses:
        alt_md += f"\n**{alt.get('hypothesis', '')}** — likelihood: `{alt.get('likelihood', 'N/A')}`\n> {alt.get('reasoning', '')}\n"

    # Similar incidents
    similar_md = ""
    for s in similar[:3]:
        m = s.get("metadata", {})
        similar_md += f"- **{m.get('title', 'N/A')}** ({m.get('date', '')}) — similarity: {s.get('similarity_score', 0):.0%}\n"

    # Confidence color indicator
    if confidence >= 85:
        conf_indicator = "🟢"
    elif confidence >= 65:
        conf_indicator = "🟡"
    else:
        conf_indicator = "🔴"

    report = f"""# 🔍 Incident Investigation Report

## Summary
**Incident:** {plan.get('incident_summary', 'Production Incident')}
**Priority:** `{plan.get('priority', 'high').upper()}`
**Severity:** `{rca.get('severity', 'high').upper()}`
**Affected Service:** `{plan.get('affected_service', 'unknown')}`

---

## {conf_indicator} Root Cause ({confidence}% Confidence)

**{root_cause.get('summary', 'Analysis in progress')}**

{root_cause.get('detailed_explanation', '')}

---

## 🧾 Evidence

{evidence_md}

---

## 🚨 Immediate Actions

{actions_md}

---

## 📊 Metrics Summary

| Metric | Value |
|--------|-------|
| Latency P99 (max) | {metrics_findings.get('raw_summary', {}).get('latency_p99_max_ms', 'N/A')} ms |
| Error Rate (max) | {metrics_findings.get('raw_summary', {}).get('error_rate_max_pct', 'N/A')} % |
| DB Connection Pool (max) | {metrics_findings.get('raw_summary', {}).get('db_connection_pool_max_pct', 'N/A')} % |
| Latency Spike Detected | {'Yes ⚠️' if metrics_findings.get('raw_summary', {}).get('latency_spike_detected') else 'No'} |
| Error Spike Detected | {'Yes ⚠️' if metrics_findings.get('raw_summary', {}).get('error_spike_detected') else 'No'} |

---

## 🚀 Suspect Deployment

| Field | Value |
|-------|-------|
| Version | `{suspect.get('version', 'N/A')}` |
| Service | `{suspect.get('service', 'N/A')}` |
| Author | {suspect.get('author', 'N/A')} |
| Change | {suspect.get('change_summary', 'N/A')} |
| Rollback Available | {'Yes ✅' if suspect.get('rollback_available') else 'No ❌'} |

---

## 🔄 Alternative Hypotheses

{alt_md if alt_md else "_No alternative hypotheses with significant likelihood._"}

---

## 📚 Similar Past Incidents (via RAG)

{similar_md if similar_md else "_No similar historical incidents found._"}

---

## 🛡️ Long-term Prevention

{prevention_md}

---

## 📋 Agent Investigation Trail

"""

    for msg in state.get("messages", []):
        role = msg.get("role", "").replace("_", " ").title()
        content = msg.get("content", "")
        report += f"- **{role}:** {content}\n"

    report += "\n---\n*Report generated by AI Incident Investigation Agent using LangGraph + Gemini + ChromaDB*"

    logger.info("[Summarizer] Report generated successfully.")

    return {
        **state,
        "final_report": report,
        "messages": state.get("messages", []) + [
            {"role": "summarizer", "content": "Final investigation report generated."}
        ],
    }
